#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Oct 24 21:40:26 2018

@author: deepak
"""
import csv as csv
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import scipy.interpolate as interpolate
import scipy.signal as signal
import scipy.ndimage as ndimage
import matplotlib.patches as patches
from numpy.polynomial import polynomial as Poly
import cmocean
import pickle
import math
import os
plt.close("all")
#==============================================================================
#                              Plot Parameters   
#==============================================================================
from matplotlib import rcParams
from matplotlib import rc
rcParams['axes.titlepad'] = 20 
rc('font',**{'family':'sans-serif','sans-serif':['Helvetica']})
## for Palatino and other serif fonts use:
#rc('font',**{'family':'serif','serif':['Palatino']})
rc('text', usetex=False)
plt.rc('font', family='serif')

freq=np.array([0.2,8,9,10,13.92,12.001,13,13.99,15,0.4999,0.9976,2.0002,3.0000,4.0001,5,6,6.9995])
phase_lag=np.array([0.067,0.9173,0.9738,1.0315,1.0766,1.1163,1.1367,1.1812,1.1957,0.1335,0.2188,0.3655,0.5047,0.6294,0.7103,0.7759,0.8456])


plt.figure()
plt.scatter(freq, -phase_lag*180/math.pi,linestyle = '-')    
    
        