#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Dec  3 22:34:55 2018

@author: deepak
"""

def fun(**kwargs):
    
    for key,value in kwargs.items():
            print(key, value)
            

A = 'arg1'
B = 20

fun(A = B)